version: '3'

services:
  db:
    container_name: nest-shop-db
    image: postgres:16.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./nest-shop-db-data:/var/lib/postgresql/data
    networks:
      - admin

  cloudbeaver:
    container_name: nest-shop-cloudbeaver
    image: dbeaver/cloudbeaver:23.3.4
    restart: unless-stopped
    ports:
      - 8978:8978
    volumes:
      - nest-shop-cloudbeaver-data:/opt/cloudbeaver/workspace
    networks:
      - admin
    depends_on:
      - db

volumes:
  nest-shop-db-data:
  nest-shop-cloudbeaver-data:

networks:
  admin:
